package Formularios;

import Identidades.DatosPerfil;
import Identidades.DatosPersonal;
import Listas.ListaPerfil;
import Listas.ListaUsuario;
import Nodos.NodoUsuario;
import Utilidades.ReportePerfil;
import javax.swing.JOptionPane;
import Utilidades.Validaciones;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Edward
 */
public class AsignarPerfil extends javax.swing.JFrame {
 
    ListaUsuario u;
    Validaciones validar;
    int[] conta;
    int swModif = 0;
    ImageIcon icoMensajeInfor, icoMensajePre;
    DatosPersonal buscarUsuario;
    DatosPerfil perfil, buscarPerfil;
    String nombreVentana;
    ListaPerfil listaPerfi;

    public AsignarPerfil() {
        initComponents();
    }

    public AsignarPerfil(ListaUsuario Lu, ListaPerfil listaPerfi) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Asignar Perfiles"); 
        u = Lu;
        validar = new Validaciones();
        conta = new int[4];
        icoMensajeInfor = new ImageIcon("C:\\OriginalPorcicolaWilbur\\src\\Imagenes\\IconoInformacion.jpg");
        icoMensajePre = new ImageIcon("C:\\OriginalPorcicolaWilbur\\src\\Imagenes\\IconoPregunta.jpg");
        jtxtNombrePerf.setEnabled(true);
        //jtxtPass.setEnabled(true);
        //jtxtConfirm.setEnabled(true);

        JComboPerfil.addItem("Administrador");
        JComboPerfil.addItem("Jaulas");
        JComboPerfil.addItem("Reportes");
        JComboPerfil.addItem("Almacen");
        JComboPerfil.addItem("Veterinario");
        this.desactivarCampos();
        this.listaPerfi = listaPerfi;
        this.validarCampos();

        nombreVentana = "Asignar Perfil - G.A.P.";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtNombrePerf = new javax.swing.JTextField();
        jtxtDocumento = new javax.swing.JTextField();
        jPassContra = new javax.swing.JPasswordField();
        jPassRepeContra = new javax.swing.JPasswordField();
        JComboPerfil = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        JBNuevo = new javax.swing.JButton();
        JButtonCrearPerfil = new javax.swing.JButton();
        JBConsultaru = new javax.swing.JButton();
        JBModificarU = new javax.swing.JButton();
        JBEliminarU = new javax.swing.JButton();
        JBListar = new javax.swing.JButton();
        JBLimpiarU = new javax.swing.JButton();
        JBVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignar Perfiles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        jLabel1.setText("Documento: ");

        jLabel2.setText("Nombre: ");

        jtxtNombre.setEnabled(false);

        jLabel8.setText("Nombre de Usuario:");

        jLabel9.setText("Contraseña: ");

        jLabel10.setText("Confirmar Contraseña: ");

        jtxtNombrePerf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtNombrePerfFocusLost(evt);
            }
        });

        jtxtDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtDocumentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtDocumentoFocusLost(evt);
            }
        });
        jtxtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDocumentoActionPerformed(evt);
            }
        });
        jtxtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDocumentoKeyTyped(evt);
            }
        });

        jPassContra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPassContraFocusLost(evt);
            }
        });
        jPassContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassContraActionPerformed(evt);
            }
        });

        jPassRepeContra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPassRepeContraFocusLost(evt);
            }
        });
        jPassRepeContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassRepeContraActionPerformed(evt);
            }
        });

        JComboPerfil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JComboPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..." }));
        JComboPerfil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboPerfilItemStateChanged(evt);
            }
        });
        JComboPerfil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JComboPerfilFocusLost(evt);
            }
        });
        JComboPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboPerfilActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("*Perfil:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboPerfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPassContra, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(jtxtNombrePerf)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPassRepeContra, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JComboPerfil, jPassContra, jPassRepeContra, jtxtDocumento, jtxtNombre, jtxtNombrePerf});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNombrePerf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JComboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jPassContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPassRepeContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(62, 62, 62))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JComboPerfil, jPassContra, jPassRepeContra, jtxtDocumento, jtxtNombre, jtxtNombrePerf});

        JBNuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Crear.png"))); // NOI18N
        JBNuevo.setToolTipText("CREAR");
        JBNuevo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNuevoActionPerformed(evt);
            }
        });

        JButtonCrearPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Guardar.png"))); // NOI18N
        JButtonCrearPerfil.setEnabled(false);
        JButtonCrearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCrearPerfilActionPerformed(evt);
            }
        });

        JBConsultaru.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBConsultaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Buscar.png"))); // NOI18N
        JBConsultaru.setToolTipText("CONSULTAR");
        JBConsultaru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBConsultaru.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBConsultaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBConsultaruActionPerformed(evt);
            }
        });

        JBModificarU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBModificarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Editar.png"))); // NOI18N
        JBModificarU.setToolTipText("MODIFICAR");
        JBModificarU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBModificarU.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBModificarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModificarUActionPerformed(evt);
            }
        });

        JBEliminarU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBEliminarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Eliminar.png"))); // NOI18N
        JBEliminarU.setToolTipText("ELIMINAR");
        JBEliminarU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBEliminarU.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBEliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarUActionPerformed(evt);
            }
        });

        JBListar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/List.png"))); // NOI18N
        JBListar.setToolTipText("LISTAR");
        JBListar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBListar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBListarActionPerformed(evt);
            }
        });

        JBLimpiarU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBLimpiarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Clear_Limpiar.png"))); // NOI18N
        JBLimpiarU.setToolTipText("LIMPIAR");
        JBLimpiarU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBLimpiarU.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBLimpiarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimpiarUActionPerformed(evt);
            }
        });

        JBVolver.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Atras.png"))); // NOI18N
        JBVolver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBVolver.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(JBNuevo)
                .addGap(18, 18, 18)
                .addComponent(JButtonCrearPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBConsultaru, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBModificarU)
                .addGap(18, 18, 18)
                .addComponent(JBEliminarU)
                .addGap(18, 18, 18)
                .addComponent(JBListar)
                .addGap(18, 18, 18)
                .addComponent(JBLimpiarU)
                .addGap(18, 18, 18)
                .addComponent(JBVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JBEliminarU, JBLimpiarU, JBListar, JBModificarU, JBNuevo, JBVolver, JButtonCrearPerfil});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBNuevo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBLimpiarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBListar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBEliminarU)))
                    .addComponent(JButtonCrearPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBConsultaru)
                    .addComponent(JBModificarU))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JBConsultaru, JBEliminarU, JBLimpiarU, JBListar, JBModificarU, JBNuevo, JBVolver, JButtonCrearPerfil});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonCrearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCrearPerfilActionPerformed

        this.guardarCamposPerfil();
        this.inicializarCont(conta);
        if (!validar.validarContraseñ(jPassContra.getText(), conta)) {

            JOptionPane.showMessageDialog(null, "La contraseña debe contener al menos un:" + "\n" + "caracter especial, letra mayuscula,"
                    + "\n" + "letra minuscula, número y un tamnaño como minimo de 8 caracteres", "Gestionar Perfil - S.G.P",
                    JOptionPane.OK_OPTION, icoMensajeInfor);
            jPassContra.requestFocus();
            jPassContra.setText("");
        } else {

            if (swModif == 0) {

                if (listaPerfi.existePerfil(perfil.getNumCedula())) {

                    JOptionPane.showMessageDialog(null, "El número ya tiene un perfil asignado", "Gestionar Perfil - S.G.P",
                            JOptionPane.OK_OPTION, icoMensajeInfor);
                } else {
                    if (listaPerfi.guardarPerfil(perfil)) {

                        JOptionPane.showMessageDialog(null, "El registro se guardo correctamente", "Gestionar Perfil - S.G.P",
                                JOptionPane.OK_OPTION, icoMensajeInfor);
                        this.limpiarCampos();
                        this.desactivarCampos();
                    } else {

                        JOptionPane.showMessageDialog(null, "El registro no fue guardado", "Gestionar Perfil - S.G.P",
                                JOptionPane.OK_OPTION, icoMensajeInfor);
                    }
                }

            } else {

                int n = JOptionPane.showConfirmDialog(this, "Esta seguro que desea modificar este registro");
                if (n == 0) {
                    if (listaPerfi.modificarPerfil(perfil)) {

                        JOptionPane.showMessageDialog(null, "El registro se modifico correctamente", "Gestionar Perfil - S.G.P",
                                JOptionPane.OK_OPTION, icoMensajeInfor);
                        this.limpiarCampos();
                        this.desactivarCampos();
                    } else {

                        JOptionPane.showMessageDialog(null, "El registro no fue modificado", "Gestionar Perfil - S.G.P",
                                JOptionPane.OK_OPTION, icoMensajeInfor);
                    }
                }
            }

            JButtonCrearPerfil.setEnabled(false);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_JButtonCrearPerfilActionPerformed

    private void jtxtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDocumentoActionPerformed
        //  this.habilitarBotonGuardar();
    }//GEN-LAST:event_jtxtDocumentoActionPerformed

    private void jtxtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDocumentoKeyTyped
        //  this.habilitarBotonGuardar();
    }//GEN-LAST:event_jtxtDocumentoKeyTyped

    private void JBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNuevoActionPerformed
        this.activarCampos();
        this.limpiarCampos();
        jtxtDocumento.setEnabled(true);
        this.desactivarBotones();
        swModif = 0;
    }//GEN-LAST:event_JBNuevoActionPerformed

    private void JBConsultaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBConsultaruActionPerformed

        swModif = 0;
        this.llenarDatos();
        this.desactivarCampos();

        // TODO add your handling code here:
    }//GEN-LAST:event_JBConsultaruActionPerformed

    private void JBModificarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModificarUActionPerformed

        swModif = 1;
        this.llenarDatos();
        this.activarCampos();
        this.desactivarBotones();

        // TODO add your handling code here:
    }//GEN-LAST:event_JBModificarUActionPerformed

    private void JBEliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarUActionPerformed

        String s = JOptionPane.showInputDialog(null, "Ingrese el número de documento del perfil que desea eliminar", "Gestionar Perfil - G.A.P.",
                JOptionPane.QUESTION_MESSAGE);
        if (listaPerfi.existePerfil(s)) {

            if (listaPerfi.eliminarPerfil(s)) {

                JOptionPane.showMessageDialog(null, "El perfil ha sido eliminado", "Gestionar Perfil - G.A.P.",
                        JOptionPane.OK_OPTION, icoMensajeInfor);
                this.limpiarCampos();

            } else {

                JOptionPane.showMessageDialog(null, "El perfil no se pudo eliminar", "Gestionar Perfil - G.A.P.",
                        JOptionPane.OK_OPTION, icoMensajeInfor);
            }
        } else {

            JOptionPane.showMessageDialog(null, "El número de documento no existe", "Gestionar Perfil - G.A.P.",
                    JOptionPane.OK_OPTION, icoMensajeInfor);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_JBEliminarUActionPerformed

    private void JBListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBListarActionPerformed

        ReportePerfil rp = new ReportePerfil(listaPerfi.getCabeza());
        // TODO add your handling code here:
    }//GEN-LAST:event_JBListarActionPerformed

    private void JBLimpiarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimpiarUActionPerformed
        this.limpiarCampos();
        this.desactivarCampos();
        this.activarBotones();
        // TODO add your handling code here:
    }//GEN-LAST:event_JBLimpiarUActionPerformed

    private void JBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVolverActionPerformed
        int opc;
        opc = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir de Asignar Perfil?",
                "Salir.  Gestión Administrativa Porcícola - G.A.P.", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, icoMensajePre);
        if (opc == 0) {
            this.dispose();

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_JBVolverActionPerformed

    private void JComboPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboPerfilActionPerformed
        //this.habilitarBotonGuardar();
    }//GEN-LAST:event_JComboPerfilActionPerformed

    private void jtxtDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtDocumentoFocusLost

        if (jtxtDocumento.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Campo obligatorio", "Asignar Perfil - G.A.P", JOptionPane.YES_OPTION,
                    icoMensajeInfor);
            jtxtDocumento.requestFocusInWindow();
        } else {
            buscarUsuario = u.cargarUsuario(jtxtDocumento.getText());
            if (buscarUsuario != null) { 

                    if (listaPerfi.existePerfil(buscarUsuario.getDocumento())) {

                        JOptionPane.showMessageDialog(null, "El usuario " + buscarUsuario.getNombre() + "\n" + "ya tiene un perfil asignado",
                                "Asignar Perfil - G.A.P", JOptionPane.YES_OPTION, icoMensajeInfor);
                        jtxtDocumento.setText("");
                        jtxtDocumento.requestFocusInWindow();
                    }else{
                        
                        jtxtNombre.setText(buscarUsuario.getNombre());
                        jtxtDocumento.transferFocus();
                    } 
            } else {

                JOptionPane.showMessageDialog(null, "Este número de documento no ha sido registrado", "Asignar Perfil - G.A.P", JOptionPane.YES_OPTION,
                        icoMensajeInfor);
                jtxtDocumento.setText("");
                this.desactivarCampos();
                this.activarBotones();
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jtxtDocumentoFocusLost

    private void jtxtDocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtDocumentoFocusGained

// TODO add your handling code here:
    }//GEN-LAST:event_jtxtDocumentoFocusGained

    private void jtxtNombrePerfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNombrePerfFocusLost

        validar.validarObligatorios(jtxtNombrePerf, nombreVentana);
// TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombrePerfFocusLost

    private void jPassContraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassContraFocusLost

        this.inicializarCont(conta);
        if (!jPassContra.getPassword().toString().equals("")) {

            if (!validar.validarContraseñ(validar.convertirPassword(jPassContra.getPassword()), conta)) {

                JOptionPane.showMessageDialog(null, "La contraseña debe contener al menos:" + "\n" + "1 caracter especial" + "\n" + "1 letra mayúscula, minúscula"
                        + "\n" + "1 número y un tamnaño como mínimo de 8 caracteres", "Asignar Perfil - S.A.P",
                        JOptionPane.OK_OPTION, icoMensajeInfor);
                jPassContra.requestFocus();
                jPassContra.setText("");
            } else {

                jPassRepeContra.requestFocusInWindow();
            }
        } else {

            JOptionPane.showMessageDialog(null, "Campo obligatorio", "Asignar Perfil - G.A.P", JOptionPane.YES_OPTION,
                    icoMensajeInfor);
            jPassContra.requestFocusInWindow();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jPassContraFocusLost

    private void JComboPerfilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboPerfilItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (JComboPerfil.getSelectedIndex() == 0) {

                JOptionPane.showMessageDialog(null, "Debe seleccionar un perfil", "Asignar Perfil - G.A.P", JOptionPane.YES_OPTION,
                        icoMensajeInfor);
                JComboPerfil.requestFocusInWindow();
            } else {

                JComboPerfil.transferFocus();
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_JComboPerfilItemStateChanged

    private void JComboPerfilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JComboPerfilFocusLost

// TODO add your handling code here:
    }//GEN-LAST:event_JComboPerfilFocusLost

    private void jPassContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassContraActionPerformed

    private void jPassRepeContraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassRepeContraFocusLost

        if (jPassRepeContra.getPassword().toString().equals("")) {

            JOptionPane.showMessageDialog(null, "Campo obligatorio", "Asignar Perfil - G.A.P", JOptionPane.YES_OPTION,
                    icoMensajeInfor);
            jPassRepeContra.requestFocusInWindow();
        } else {

            if (!validar.convertirPassword(jPassRepeContra.getPassword()).equals(validar.convertirPassword(jPassContra.getPassword()))) {

                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Asignar Perfil - G.A.P", JOptionPane.YES_OPTION,
                        icoMensajeInfor);
                jPassRepeContra.requestFocusInWindow();
                jPassRepeContra.setText("");
            } else {

                if (jtxtDocumento.getText().equals("") || jtxtNombre.getText().equals("") || jtxtNombrePerf.getText().equals("")
                        || jPassContra.getText().equals("") || jPassRepeContra.getText().equals("")){

                    JOptionPane.showMessageDialog(null, "Digite todos los campos obligatorios", "Gestionar Perfil - S.G.P",
                            JOptionPane.OK_OPTION, icoMensajeInfor);
                    jPassRepeContra.requestFocusInWindow();
                } else {
                    this.desactivarCampos();
                    JButtonCrearPerfil.setEnabled(true);
                }
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jPassRepeContraFocusLost

    private void jPassRepeContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassRepeContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassRepeContraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBConsultaru;
    private javax.swing.JButton JBEliminarU;
    private javax.swing.JButton JBLimpiarU;
    private javax.swing.JButton JBListar;
    private javax.swing.JButton JBModificarU;
    private javax.swing.JButton JBNuevo;
    private javax.swing.JButton JBVolver;
    private javax.swing.JButton JButtonCrearPerfil;
    private javax.swing.JComboBox JComboPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassContra;
    private javax.swing.JPasswordField jPassRepeContra;
    private javax.swing.JTextField jtxtDocumento;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtNombrePerf;
    // End of variables declaration//GEN-END:variables

    public void inicializarCont(int cont[]) {

        for (int j = 0; j < 3; j++) {

            cont[j] = 0;
        }
    }

    public void guardarCamposPerfil() {

        perfil = new DatosPerfil();
        perfil.setNumCedula(jtxtDocumento.getText());
        perfil.setNombre(jtxtNombre.getText());
        perfil.setPerfil((String) JComboPerfil.getSelectedItem());
        perfil.setUsuario(jtxtNombrePerf.getText());
        perfil.setContraIngreso(jPassContra.getText());
        perfil.setRepetirContraIngreso(jPassRepeContra.getText());
    }

    public void desactivarCampos() {

        jtxtDocumento.setEnabled(false);
        jtxtNombre.setEnabled(false);
        jtxtNombrePerf.setEnabled(false);
        JComboPerfil.setEnabled(false);
        jPassContra.setEnabled(false);
        jPassRepeContra.setEnabled(false);
    }

    public void activarCampos() {

        jtxtNombrePerf.setEnabled(true);
        JComboPerfil.setEnabled(true);
        jPassContra.setEnabled(true);
        jPassRepeContra.setEnabled(true);
    }

    public void limpiarCampos() {

        jtxtDocumento.setText("");
        jtxtNombre.setText("");
        jtxtNombrePerf.setText("");
        JComboPerfil.setSelectedItem(0);
        jPassContra.setText("");
        jPassRepeContra.setText("");
    }

    public void desactivarBotones() {

        JBNuevo.setEnabled(false);
        JBModificarU.setEnabled(false);
        JBConsultaru.setEnabled(false);
        JBEliminarU.setEnabled(false);
        JBListar.setEnabled(false);
    }

    public void activarBotones() {

        JBNuevo.setEnabled(true);
        JBModificarU.setEnabled(true);
        JBConsultaru.setEnabled(true);
        JBEliminarU.setEnabled(true);
        JBListar.setEnabled(true);
    }

    public void llenarDatos() {

        int opc = -2;
        String[] opciones = {"Número de Documento", "Nombre Usuario", "Nombre"};
        if (swModif == 1) {

            buscarPerfil = listaPerfi.BuscarPerfil(JOptionPane.showInputDialog("Ingrese el número de documento del registro a modificar"));
            this.activarCampos();
            this.desactivarBotones();
        } else {

            opc = JOptionPane.showOptionDialog(null, "Seleccione la forma en que desea realizar la consulta",
                    "Consulta de Personal. Sistematización Granjas Porcícola - S.G.P.", JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE, icoMensajePre, opciones, true);
            switch (opc) {

                case 0:
                    buscarPerfil = listaPerfi.BuscarPerfil(JOptionPane.showInputDialog("Ingrese el número de documento del personal a consultar"));
                    break;
                case 1:
                    buscarPerfil = listaPerfi.BuscarPerfilNomUsuario(JOptionPane.showInputDialog("Ingrese el nombre del personal a consultar"));
                    break;
                case 2:
                    buscarPerfil = listaPerfi.BuscarPerfilUsuario(JOptionPane.showInputDialog("Ingrese el correo del personal a consultar"));
                    break;
            }
        }
        if (opc != -1) {

            if (buscarPerfil != null) {

                jtxtDocumento.setText(buscarPerfil.getNumCedula());
                jtxtNombre.setText(buscarPerfil.getNombre());
                JComboPerfil.setSelectedItem(buscarPerfil.getPerfil());
                jtxtNombrePerf.setText(buscarPerfil.getUsuario());
                jPassContra.setText(buscarPerfil.getContraIngreso());
                jPassRepeContra.setText(buscarPerfil.getRepetirContraIngreso());
            } else {

                JOptionPane.showMessageDialog(null, "El registro no existe", "Gestionar Personal - G.A.P",
                        JOptionPane.OK_OPTION, icoMensajeInfor);
                this.activarBotones();
            }
        } else {

            JOptionPane.showMessageDialog(null, "Se cancelo la consulta", "Gestionar Personal - G.A.P",
                    JOptionPane.OK_OPTION, icoMensajeInfor);
        }
        buscarUsuario = null;
    }

    public void validarCampos() {
        jtxtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                validar.validarLongitud(10, jtxtDocumento, e);
                validar.soloNumeros(jtxtDocumento, e);
            }
        });
        this.jtxtNombrePerf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                validar.validarLongitud(10, jtxtNombrePerf, e);
            }
        });
        this.jPassContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                validar.validarLongitudPas(12, jPassContra, e);
            }
        });
        this.jPassRepeContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                validar.validarLongitudPas(12, jPassRepeContra, e);
            }
        });

    }
}
