/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import porcicolawilbur.*;
import Identidades.*;
import Listas.*;
import Utilidades.ReportePartos;
import Utilidades.Validaciones;

/**
 *
 * @author Administrador
 */
public class JFramePartos extends javax.swing.JFrame {

    Granja parto, buscarParto;
    ListaPartos listaParto;
    ImageIcon icoMensajeInfor, icoMensajePre, icoCalendario;
    Validaciones va;
    int swModDatosParto = 0;
    String nombreVentana;
    ListaAnimal listaAnimal;
    DatosAnimal buscarAnimal;

    public JFramePartos() {
        initComponents();

    }

    public JFramePartos(ListaPartos P, ListaAnimal listaAnimal) {
        initComponents();
        this.validarCampos();
        this.setVisible(true);
        this.listaParto = P;
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Gestionar Partos");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/1_Icono_Form.JPG")).getImage());
        icoMensajeInfor = new ImageIcon("C:\\OriginalPorcicolaWilbur\\src\\Imagenes\\IconoInformacion.jpg");
        icoMensajePre = new ImageIcon("C:\\OriginalPorcicolaWilbur\\src\\Imagenes\\IconoPregunta.jpg");
        icoCalendario = new ImageIcon("C:\\OriginalPorcicolaWilbur\\src\\Imagenes\\iconoCalendario.jpg");

        this.ComboRaza.addItem("Hampshire");
        this.ComboRaza.addItem("Duroc");
        this.ComboRaza.addItem("Pietrain");
        this.ComboRaza.addItem("Landrace");
        this.ComboRaza.addItem("Yorkshire (Large White)");

        va = new Validaciones();
        parto = new Granja();
        buscarParto = new Granja();
        nombreVentana = "Datos Partos - G.A.P";
        this.listaAnimal = listaAnimal;

        jdFechaParto.setIcon(icoCalendario);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlCodigoParto = new javax.swing.JLabel();
        JlFechaParto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JBGuardar = new javax.swing.JButton();
        JBModificar = new javax.swing.JButton();
        JBConsultar = new javax.swing.JButton();
        JBEliminar = new javax.swing.JButton();
        jdFechaParto = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        JlCodigo = new javax.swing.JLabel();
        JtCodigo = new javax.swing.JTextField();
        ComboRaza = new javax.swing.JComboBox();
        JlRaza = new javax.swing.JLabel();
        JlEdad = new javax.swing.JLabel();
        JTEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JlRaza1 = new javax.swing.JLabel();
        ComboRazaPadre = new javax.swing.JComboBox();
        JBNuevo = new javax.swing.JButton();
        JBLimpiar = new javax.swing.JButton();
        Jtcodigoparto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JBVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JlNumeroVivos = new javax.swing.JLabel();
        JTNroVivos = new javax.swing.JTextField();
        JlNumeroMuertos = new javax.swing.JLabel();
        JTNroMuertos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JTCamada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Gestionar Partos"); // NOI18N

        JlCodigoParto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlCodigoParto.setText("   *Código del Parto");

        JlFechaParto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlFechaParto.setText("*Fecha del Parto");

        JBGuardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Guardar.png"))); // NOI18N
        JBGuardar.setEnabled(false);
        JBGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarActionPerformed(evt);
            }
        });

        JBModificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Editar.png"))); // NOI18N
        JBModificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBModificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModificarActionPerformed(evt);
            }
        });

        JBConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Buscar.png"))); // NOI18N
        JBConsultar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBConsultarActionPerformed(evt);
            }
        });

        JBEliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Eliminar.png"))); // NOI18N
        JBEliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });

        jdFechaParto.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Identificación de la Madre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        JlCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlCodigo.setText("*Código Madre");

        JtCodigo.setEnabled(false);
        JtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JtCodigoFocusLost(evt);
            }
        });
        JtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtCodigoActionPerformed(evt);
            }
        });

        ComboRaza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..." }));
        ComboRaza.setEnabled(false);
        ComboRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRazaActionPerformed(evt);
            }
        });

        JlRaza.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlRaza.setText(" Raza Madre");

        JlEdad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlEdad.setText("  Edad");

        JTEdad.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Semanas");

        JlRaza1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlRaza1.setText(" Raza Padre");

        ComboRazaPadre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..." }));
        ComboRazaPadre.setEnabled(false);
        ComboRazaPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRazaPadreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(63, 63, 63)
                        .addComponent(JlRaza1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ComboRazaPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(JlRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ComboRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JlEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlRaza1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ComboRazaPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        JBNuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Crear.png"))); // NOI18N
        JBNuevo.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        JBNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNuevoActionPerformed(evt);
            }
        });

        JBLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Clear_Limpiar.png"))); // NOI18N
        JBLimpiar.setToolTipText("Limpiar Campos");
        JBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimpiarActionPerformed(evt);
            }
        });

        Jtcodigoparto.setEnabled(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Icono_Form.JPG"))); // NOI18N

        JBVolver.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JBVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1_Atras.png"))); // NOI18N
        JBVolver.setToolTipText("Volver al Menu Principal");
        JBVolver.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVolverActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Lechones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        JlNumeroVivos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlNumeroVivos.setText("*Número de Vivos");

        JTNroVivos.setEnabled(false);
        JTNroVivos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTNroVivosFocusLost(evt);
            }
        });
        JTNroVivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNroVivosActionPerformed(evt);
            }
        });

        JlNumeroMuertos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JlNumeroMuertos.setText("*Número de Muertos");

        JTNroMuertos.setEnabled(false);
        JTNroMuertos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTNroMuertosFocusLost(evt);
            }
        });
        JTNroMuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNroMuertosActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Total Camada");

        JTCamada.setEnabled(false);
        JTCamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTCamadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JlNumeroVivos)
                        .addGap(10, 10, 10)
                        .addComponent(JTNroVivos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(JTCamada)))
                .addGap(122, 122, 122)
                .addComponent(JlNumeroMuertos)
                .addGap(10, 10, 10)
                .addComponent(JTNroMuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlNumeroVivos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlNumeroMuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTNroVivos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTNroMuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTCamada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("(*) Campos Obligatorios");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/List.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(JBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(JBLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(JlCodigoParto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jtcodigoparto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(JlFechaParto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdFechaParto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JBConsultar, JBEliminar, JBGuardar, JBLimpiar, JBModificar, JBNuevo, JBVolver, jButton1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdFechaParto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jtcodigoparto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JlFechaParto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JlCodigoParto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBVolver)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(JBLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBConsultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTNroMuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNroMuertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNroMuertosActionPerformed

    private void JBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModificarActionPerformed

        swModDatosParto = 1;
        this.LlenarDatos();
// TODO add your handling code here:
    }//GEN-LAST:event_JBModificarActionPerformed

    private void JBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarActionPerformed

        parto = this.GuardarCampos();
        if (swModDatosParto == 0) {
            if (!listaParto.existe(parto.getCodPart())) {

                if (listaParto.guardarParto(parto)) {
                    JOptionPane.showMessageDialog(this, "Se Guardo Correctamente", "Gestionar Partos - G.A.P", JOptionPane.YES_NO_OPTION,
                            icoMensajePre);
                    this.LimpiarCampos();
                    this.DesactivarCampos();
                    this.activarBotones();

                } else {
                    JOptionPane.showMessageDialog(this, "No Se pudo guardar correctamete", "Gestionar Partos - G.A.P", JOptionPane.YES_NO_OPTION,
                            icoMensajePre);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Este Parto ya existe", "Gestionar Partos - G.A.P", JOptionPane.YES_NO_OPTION,
                        icoMensajePre);
            }
        } else {
            int opc;
            opc = JOptionPane.showConfirmDialog(null, "Esta seguro que desea modificar este registro",
                    "Gestionar Partos - G.A.P", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, icoMensajePre);
            if (opc == 0) {
                if (listaParto.modificarParto(parto)) {

                    JOptionPane.showMessageDialog(null, "El registro se modifico correctamente", "Gestionar Partos - G.A.P",
                            JOptionPane.OK_OPTION, icoMensajeInfor);
                    this.LimpiarCampos();
                    this.DesactivarCampos();
                } else {

                    JOptionPane.showMessageDialog(null, "El registro no fue modificado", "Gestionar Partos - G.A.P",
                            JOptionPane.OK_OPTION, icoMensajeInfor);
                }
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_JBGuardarActionPerformed

    private void JBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBConsultarActionPerformed

        swModDatosParto = 0;
        this.LlenarDatos();
    }//GEN-LAST:event_JBConsultarActionPerformed

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed

        String s = JOptionPane.showInputDialog(this, "Ingrese el codigo del parto a eliminar");

        if (listaParto.existe(s)) {
            JOptionPane.showMessageDialog(this, "Esta seguro que desea eliminar este parto", "Gestionar Partos - G.A.P", JOptionPane.YES_NO_OPTION,
                    icoMensajePre);
            if (listaParto.eliminarParto(s)) {
                JOptionPane.showMessageDialog(this, "Se a eliminado correctamente", "Gestionar Partos - G.A.P", JOptionPane.YES_NO_OPTION,
                        icoMensajePre);
                this.LimpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "no se pudo eliminar el parto", "Gestionar Partos - G.A.P", JOptionPane.YES_NO_OPTION,
                        icoMensajePre);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El parto no existe", "Gestionar Partos - G.A.P", JOptionPane.YES_NO_OPTION,
                    icoMensajePre);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_JBEliminarActionPerformed

    private void JtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtCodigoActionPerformed

    private void JTCamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTCamadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCamadaActionPerformed

    private void JTNroVivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNroVivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNroVivosActionPerformed

    private void ComboRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRazaActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_ComboRazaActionPerformed

    private void JBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVolverActionPerformed
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_JBVolverActionPerformed

    private void JBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNuevoActionPerformed
        int Cod = listaParto.NuevoCod();
        Jtcodigoparto.setText(this.codigoAnimales(Cod));
        this.ActivarCampos();
        JtCodigo.requestFocusInWindow();
        this.desactivarBotones();
        jdFechaParto.setDate(new Date());
// TODO add your handling code here:
    }//GEN-LAST:event_JBNuevoActionPerformed

    private void JBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimpiarActionPerformed

        this.LimpiarCampos();
        this.DesactivarCampos();
        this.activarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_JBLimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ReportePartos(listaParto.getPrimero());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JtCodigoFocusLost

        if (JtCodigo.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Campo obligatorio", "Datos Partos - G.A.P", JOptionPane.YES_OPTION,
                    icoMensajeInfor);
            JTNroMuertos.requestFocusInWindow();
        } else {
            buscarAnimal = listaAnimal.verificarReproductora(JtCodigo.getText());
            if (buscarAnimal != null) {

                ComboRaza.setSelectedItem(buscarAnimal.getRazaMadre());
                JTEdad.setText(buscarAnimal.getEdad_sem());
                JtCodigo.transferFocus();
            } else {

                JOptionPane.showMessageDialog(null, "El codigo de la madre no existe", "Datos Partos - G.A.P", JOptionPane.YES_OPTION,
                        icoMensajeInfor);
                JtCodigo.requestFocusInWindow();
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_JtCodigoFocusLost

    private void JTNroVivosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTNroVivosFocusLost

        va.validarObligatorios(JTNroVivos, nombreVentana);
// TODO add your handling code here:
    }//GEN-LAST:event_JTNroVivosFocusLost

    private void JTNroMuertosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTNroMuertosFocusLost

        if (JTNroMuertos.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Campo obligatorio", "Datos Partos - G.A.P", JOptionPane.YES_OPTION,
                    icoMensajeInfor);
            JTNroMuertos.requestFocusInWindow();
        } else {

            JTCamada.setText(Integer.toString(Sumatoria(JTNroVivos, JTNroMuertos)));
            this.DesactivarCampos();
            this.validarObligatorios();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_JTNroMuertosFocusLost

    private void ComboRazaPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRazaPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboRazaPadreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePartos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboRaza;
    private javax.swing.JComboBox ComboRazaPadre;
    private javax.swing.JButton JBConsultar;
    private javax.swing.JButton JBEliminar;
    private javax.swing.JButton JBGuardar;
    private javax.swing.JButton JBLimpiar;
    private javax.swing.JButton JBModificar;
    private javax.swing.JButton JBNuevo;
    private javax.swing.JButton JBVolver;
    private javax.swing.JTextField JTCamada;
    private javax.swing.JTextField JTEdad;
    private javax.swing.JTextField JTNroMuertos;
    private javax.swing.JTextField JTNroVivos;
    private javax.swing.JLabel JlCodigo;
    private javax.swing.JLabel JlCodigoParto;
    private javax.swing.JLabel JlEdad;
    private javax.swing.JLabel JlFechaParto;
    private javax.swing.JLabel JlNumeroMuertos;
    private javax.swing.JLabel JlNumeroVivos;
    private javax.swing.JLabel JlRaza;
    private javax.swing.JLabel JlRaza1;
    private javax.swing.JTextField JtCodigo;
    private javax.swing.JTextField Jtcodigoparto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdFechaParto;
    // End of variables declaration//GEN-END:variables
public void LimpiarCampos() {
        JTCamada.setText("");
        JTEdad.setText("");
        JTNroVivos.setText("");
        JTNroMuertos.setText("");
        JtCodigo.setText("");
        Jtcodigoparto.setText("");
        jdFechaParto.setDate(null);
        ComboRaza.setSelectedItem(null);
    }

    public Granja GuardarCampos() {
        Granja p2 = new Granja();
        p2.setCodPart(Jtcodigoparto.getText());
        p2.setCodigo(JtCodigo.getText());
        p2.setEdad(JTEdad.getText());
        p2.setNroVivos(JTNroVivos.getText());
        p2.setNroMuertos(JTNroMuertos.getText());
        p2.setTotcamada(JTCamada.getText());
        p2.setFechaParto(jdFechaParto.getDate());
        p2.setRaza((String) ComboRaza.getSelectedItem());

        return p2;

    }

    public void LlenarDatos() {

        int opc = -2;
        String[] opciones = {"Código Parto", "Código Madre", "Correo"};
        if (swModDatosParto == 1) {

            buscarParto = listaParto.cargarParto(JOptionPane.showInputDialog("Ingrese el número de documento del registro a modificar"));
            this.ActivarCampos();
            this.desactivarBotones();
        } else {

            opc = JOptionPane.showOptionDialog(null, "Seleccione la forma en que desea realizar la consulta",
                    "Consulta de Personal. Sistematización Granjas Porcícola - S.G.P.", JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE, icoMensajePre, opciones, true);
            switch (opc) {

                case 0:
                    buscarParto = listaParto.cargarParto(JOptionPane.showInputDialog("Ingrese el número de documento del personal a consultar"));
                    break;
                case 1:
                    buscarParto = listaParto.cargarPartoCodigoMadre(JOptionPane.showInputDialog("Ingrese el nombre del personal a consultar"));
                    break;
                case 2:
                    buscarParto = listaParto.cargarParto(JOptionPane.showInputDialog("Ingrese el correo del personal a consultar"));
                    break;
            }
        }
        if (opc != -1) {

            if (buscarParto != null) {
                Jtcodigoparto.setText(buscarParto.getCodPart());
                JtCodigo.setText(buscarParto.getCodigo());
                JTEdad.setText(buscarParto.getEdad());
                JTNroVivos.setText(buscarParto.getNroVivos());
                JTNroMuertos.setText(buscarParto.getNroMuertos());
                JTCamada.setText(buscarParto.getTotcamada());
                jdFechaParto.setDate(buscarParto.getFechaParto());
                ComboRaza.setSelectedItem(buscarParto.getRaza());
            } else {

                JOptionPane.showMessageDialog(null, "El registro no existe", "Gestionar Personal - G.A.P",
                        JOptionPane.OK_OPTION, icoMensajeInfor);
                this.activarBotones();
            }
        } else {

            JOptionPane.showMessageDialog(null, "Se cancelo la consulta", "Gestionar Personal - G.A.P",
                    JOptionPane.OK_OPTION, icoMensajeInfor);
        }
        buscarParto = null;

    }

    public void DesactivarCampos() {
        Jtcodigoparto.setEnabled(false);
        JtCodigo.setEnabled(false);
        JTEdad.setEnabled(false);
        JTNroVivos.setEnabled(false);
        JTNroMuertos.setEnabled(false);
        JTCamada.setEnabled(false);
        jdFechaParto.setEnabled(false);

    }

    public void ActivarCampos() {

        JtCodigo.setEnabled(true);
        JTEdad.setEnabled(true);
        JTNroVivos.setEnabled(true);
        JTNroMuertos.setEnabled(true);
        ComboRaza.setEnabled(true);
    }

    public void desactivarBotones() {

        //JBGuardarU.setEnabled(false);
        JBNuevo.setEnabled(false);
        JBModificar.setEnabled(false);
        JBConsultar.setEnabled(false);
        JBEliminar.setEnabled(false);
        JBVolver.setEnabled(false);
        jButton1.setEnabled(false);
    }

    public void activarBotones() {

        JBNuevo.setEnabled(true);
        JBModificar.setEnabled(true);
        JBConsultar.setEnabled(true);
        JBEliminar.setEnabled(true);
        JBVolver.setEnabled(true);
        jButton1.setEnabled(true);
    }

    public void validarCampos() {
        JtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                va.validarLongitud(2, JtCodigo, e);
                va.soloNumeros(JtCodigo, e);
            }
        });

        this.Jtcodigoparto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                va.validarLongitud(2, Jtcodigoparto, e);
                va.soloNumeros(Jtcodigoparto, e);
            }
        });
        this.JTCamada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                va.validarLongitud(2, JTCamada, e);
                va.soloNumeros(JTCamada, e);
            }
        });
        this.JTEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                va.validarLongitud(3, JTEdad, e);
                va.soloNumeros(JTEdad, e);
            }
        });
        this.JTNroMuertos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                va.validarLongitud(2, JTNroMuertos, e);
                va.soloNumeros(JTNroMuertos, e);
            }
        });
        this.JTNroVivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                va.validarLongitud(2, JTNroVivos, e);
                va.soloNumeros(JTNroVivos, e);
            }
        });
    }

    public String codigoAnimales(int contador) {

        int op;
        String longitud, codigo = "";
        longitud = String.valueOf(contador);
        op = longitud.length();
        switch (op) {

            case 1:
                codigo = "000" + longitud;
                break;
            case 2:
                codigo = "00" + longitud;
                break;
            case 3:
                codigo = "0" + longitud;
            case 4:
                codigo = longitud;
                break;
        }
        return codigo;
    }

    public int Sumatoria(JTextField V, JTextField M) {

        String Vivos, Muertos;
        int Camada;

        Vivos = V.getText();
        Muertos = M.getText();

        int Viv = Integer.parseInt(Vivos);
        int Muert = Integer.parseInt(Muertos);

        Camada = Viv + Muert;

        return Camada;

        //  String Cam=Double.toString(Camada);
    }

    public void validarObligatorios() {

        if (Jtcodigoparto.getText().equals("") || JtCodigo.getText().equals("") || JTNroVivos.getText().equals("")
                || JTNroMuertos.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Ingrese todos los campos obligatorios", "Gestionar Partos - G.A.P",
                    JOptionPane.OK_OPTION, icoMensajeInfor);
            JTNroMuertos.requestFocusInWindow();
        }else{
            
            JBGuardar.setEnabled(true);
        }
    }

}
